# Generated by Django 3.0.8 on 2020-08-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17)),
                ('description', models.CharField(max_length=35)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deliveryPrice', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'Products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=9)),
                ('description', models.CharField(blank=True, max_length=23)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.Products')),
            ],
            options={
                'db_table': 'ProductOptions',
                'managed': True,
            },
        ),
    ]
