# Generated by Django 3.0.8 on 2020-08-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_auto_20200827_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptions',
            name='productId',
            field=models.CharField(max_length=36),
        ),
    ]
